
      <li{if $used_home != ""} {$used_home} {else} {$topmenu} {/if}><a href="/fr/profile/index.html?{$sid}" title="Maison" style="height:32px;line-height:32px;"><img src="/templates/css/house_32x32.png" alt=""/>Maison</a></li>
      <li{if $used_server != ""} {$used_server} {else} {$topmenu} {/if}><a href="/fr/profile/server.html?{$sid}" title="Gérer votre Serveur" style="height:32px;line-height:32px;"><img src="/templates/css/server_32x32.png" alt=""/>Serveur</a></li>
      <li{if $used_replace != ""} {$used_replace} {else} {$topmenu} {/if}><a href="/fr/profile/replace.html?{$sid}" title="Remplacer les données dans le rapport" style="height:32px;line-height:32px;"><img src="/templates/css/trackback_32x32.png" alt=""/>Remplacer</a></li>
      <li{if $used_whitelist != ""} {$used_whitelist} {else} {$topmenu} {/if}><a href="/fr/profile/whitelist.html?{$sid}" title="Whitelist" style="height:32px;line-height:32px;"><img src="/templates/css/note_32x32.png" alt=""/>Whitelist</a>   </li>
      <li{if $used_statistics != ""} {$used_statistics} {else} {$topmenu} {/if}><a href="/fr/profile/statistics.html?{$sid}" title="Statistiques votre Serveur" style="height:32px;line-height:32px;"><img src="/templates/css/line_graph_32x32.png" alt=""/>Statistiques</a></li>
      <li{if $used_allstats != ""} {$used_allstats} {else} {$topmenu} {/if}><a href="/fr/profile/allstats.html?{$sid}" title="Statistiques de tous les utilisateurs" style="height:32px;line-height:32px;"><img src="/templates/css/line_chart_32x32.png" alt=""/>User-/Server-Stats</a></li>
      <li{if $used_change != ""} {$used_change} {else} {$topmenu} {/if}><a href="/fr/profile/change.html?{$sid}" title="Votre profil et paramètres (Newsletter...)" style="height:32px;line-height:32px;"><img src="/templates/css/user_32x32.png" alt=""/>Profil</a></li>
      <li{if $used_reports != ""} {$used_reports} {else} {$topmenu} {/if}><a href="/fr/profile/reports.html?{$sid}" title="Rapports sommaires de vos attaques signalées" style="height:32px;line-height:32px;"><img src="/templates/css/script_32x32.png" alt=""/>Rapports</a></li>
      <li{if $used_logout != ""} {$used_logout} {else} {$topmenu} {/if}><a href="/fr/profile/logout.html?{$sid}" title="Se déconnecter" style="height:32px;line-height:32px; color: red;"><img src="/templates/css/unlock_32x32.png" alt=""/>Se déconnecter</a></li>
      <li{if $used_main != ""} {$used_main} {else} {$topmenu} {/if}><a href="/fr/index.html" title="Accueil sans Déconnexion" style="height:32px;line-height:32px;"><img src="/templates/css/door_32x32.png" alt=""/>Accueil sans Déconnexion</a></li>


