Hello Abuse-Team,

your Server/Customer with the IP: *'.$ip.'* has attacked one of our servers/partners.
The attackers used the method/service: *'.$tdienst.'*  on: *'.$datum.'*.
The time listed is from the server-time of the Blocklist-user who submitted the report.
The attack was reported to the Blocklist.de-System on: *'.$this->mytime.'*


!!! Do not answer to this Mail! Use support@ or contact-form !!!


The IP has been automatically blocked for a period of time. For an IP to be blocked, it needs
to have made several failed logins (ssh, imap....), tried to log in for an "invalid user", or have
triggered several 5xx-Error-Codes (eg. Blacklist on email...), all during a short period of time.
The Server-Owner configures the number of failed attempts, and the time period they have
to occur in, in order to trigger a ban and report. Blocklist has no control over these settings.
'.$bots2.'

Please check the machine behind the IP '.$ip.' ('.$host.') and fix the problem.
'.$matchs.'

If you need the logs in another format (rather than an attachment), please let us know.
You can see the Logfiles online again: https://www.blocklist.de/en/logs.html?rid={RID}&ip='.$ip.'


You can parse this abuse report mail with X-ARF-Tools from http://www.x-arf.org/tools.html e.g. validatexarf-php.tar.gz.
You can find more information about X-Arf V0.2 at http://www.x-arf.org/specification.html

This message will be sent again in one day if more attacks are reported to Blocklist.
In the attachment of this message you can find the original logs from the attacked system.

To pause this message for one week, you can use our "Stop Reports" feature on Blocklist.de to submit
the IP you want to stop recieving emails about, and the email you want to stop receiving them on.
If more attacks from your network are recognized after the seven day grace period, the reports will start
being sent again.

To pause these reports for one week:
{LINK}


We found this abuse email address '.$fund.'
Reply to this message to let us know if you want us to send future reports to a different email. (e.g. to abuse-quiet or a special address)
{REWRITE}
{LOGS2}
------------------------------
blocklist.de Abuse-Team
This message was sent automatically. For questions please use our Contact-Form (autogenerated@/abuse-team@ is not monitored!):
https://www.blocklist.de/en/contact.html?RID={RID}
Logfiles: https://www.blocklist.de/en/logs.html?rid={RID}&ip='.$ip.'
------------------------------

