<?php

$langs['title_export'] = 'www.blocklist.de -- Export all Attacker-IPs from the last 48 Hours.';
$langs['title_home'] = 'www.blocklist.de -- Fail2Ban-Reporting Service (we send Reports from Attacks on Postfix, SSH, Apache-Attacks, Spambots, irc-Bots, Reg-Bots, DDos and more) from Fail2Ban via X-ARF.';
$langs['title_index'] = 'title_home';
$langs['title_contact'] = 'Contactform, ask us or send us your Server-Data to send Report over us.';
$langs['title_partners'] = 'www.blocklist.de -- our Partners, who send us Fail2Ban-Reports';
$langs['title_statistics'] = 'www.blocklist.de -- Statistics about the last Attacks from IP, ASN, Coountry.... and more.';
$langs['title_statisticsmonth'] = 'Statistics about the Attacks from only the current month (IPs, ASN, Countrys...).';
$langs['title_graph'] = 'Graphical Statistics over our Attacks (for which Service) and sum our Reports';
$langs['title_insert'] = 'www.blocklist.de -- Stop Reports for a IP and E-Mail-Address for 7 Days to fix the Problem.';
$langs['title_servergraph'] = 'Graphical statistics about attacks on individual servers.';
$langs['title_login'] = 'Login to your Account on www.blocklist.de';
$langs['title_register'] = 'Cr&amp;eacute;er un compte sur www.blocklist.de';
$langs['title_register1'] = 'Confirmer votre inscription sur www.blocklist.fr';
$langs['title_register2'] = 'Blocking e-mail addresses for registration on www.blocklist.de';
$langs['title_resend'] = 'Renvoyer le mail de confirmation de blocklist.de';
$langs['title_password'] = 'Cr&amp;eacute;er un nouveau mot de passe pour votre compte sur blocklist.de.';
$langs['title_replace'] = 'www.blocklist.de -- Replace automatically Data from your Reports.';
$langs['title_whitelist'] = 'Ajouter votre adresse IP &amp;agrave; la liste blanche de blocklist.de';
$langs['title_downloads'] = 'Download our Reporting-Scripts to send your Reports self (in proccess).';
$langs['title_allstats'] = 'www.blocklist.de -- All User on one Statistic for comparison)';
$langs['title_data'] = 'Change your Profile/Settings.';
$langs['title_profil'] = 'www.blocklist.de -- Your Customer-Login for your Account on blocklist.de';
$langs['title_server'] = 'Votre serveurs enregistr&amp;eacute; sur blocklist.de';
$langs['title_serverstats'] = 'Statistiques graphiques sur les attaques sur votre serveurs.';
$langs['title_imprint'] = 'Imprim&amp;eacute; depuis www.blocklist.de';
$langs['title_terms'] = 'Terms and private Policy for an Account on blocklist.de';
$langs['title_delete'] = 'Delete your Account from www.blocklist.de.';
$langs['title_list'] = 'Show Attacks on your Server';
$langs['title_api'] = 'API from www.blocklist.de. Show Server- or all User-Statistics for your own Homepage/Scripts';
$langs['title_reports'] = 'summary Reports from the Attacks and Reports from your Server.';
$langs['title_delist'] = 'Delete your IP from the 24h List earlier.';
$langs['title_httpapi'] = 'IP-Adressen/Angreifer per http (GET/POST) melden.';
$langs['error_one'] = 'Il y avait une erreur.';
$langs['error_more'] = 'Plusieurs erreurs se sont produites.';
$langs['error_db'] = 'Could not enter the data into the database. Please try again!';
$langs['error_system'] = 'Unfortunately, the data given do not agree with the system.';
$langs['error_mail'] = 'Sorry, could not connect to the Mailserver. Please try again.';
$langs['contact_typ'] = 'S&amp;eacute;lectionnez un sujet svp.';
$langs['contact_mitteilung1'] = 'Ins&amp;eacute;rez votre question ou vos donn&amp;eacute;es.';
$langs['contact_mitteilung2'] = 'Utilisez plus de 15 signes, s\'il-vous-plait!';
$langs['contact_sender1'] = 'Entrez votre adresse d\'exp&amp;eacute;diteur Fail2Ban (adresse de retour configur&amp;eacute;e dans jail.conf).';
$langs['contact_sender2'] = '??? ????? ?????? ??????? (?????????: mailbox@domain.tld)!';
$langs['contact_daten'] = 'Indtast venligst din afsender IP!';
$langs['contact_display'] = 'Indtast venligst din sk?rm navn!';
$langs['contact_email1'] = 'Indtast venligst din e-mail-adresse til svar.';
$langs['contact_email2'] = 'contact_sender2';
$langs['contact_server'] = 'Please insert the amount of servers you have.';
$langs['contact_error'] = 'Fejl! Tjek venligst dine data.';
$langs['contact_noip'] = 'IP-????? ?? ???????? ??????? IPv4 ??? IPv6';
$langs['contact_noja'] = 'S\'il vous pla&amp;icirc;t confirmez avec &quot;JA&quot;.';
$langs['contact_noja2'] = 'Please insert exact JA';
$langs['contact_rid'] = 'The RID is only numeric.';
$langs['search_counterreset'] = '<small>(this month)</small>';
$langs['search_counterreset2'] = '<small>(ganzer Zeitraum)</small>';
$langs['search_ip'] = 'Please insert an IP-address or an AS-number';
$langs['search_nofound'] = 'Aucun r&amp;eacute;sultat pour cette recherche';
$langs['search_as'] = 'S\'il vous pla&amp;icirc;t Entrez un num&amp;eacute;ro AS';
$langs['search_notuse'] = 'not in use';
$langs['search_noipv4'] = 'Votre IP n\'est pas correcte (ipV4 uniquement).';
$langs['search_takealook'] = 'Please take also a look to <a href=&quot;http://honeystats.info/glastopf_rbldnsd.zone&quot; title=&quot;Honeystats.info RFI-Attacks&quot;&quot;>http://honeystats.info/</a> if your Search returns no matches.';
$langs['insert_email'] = 'Please insert an abuse-address';
$langs['insert_emailnotyour'] = 'The Address is used by a other User';
$langs['insert_ok1'] = 'For the IP will be never send Reports already to date:';
$langs['insert_ok2'] = 'For the IP and Abuse-Address we dont send longer now Reports to date:';
$langs['insert_ok3'] = 'For the IP and Abuse-Address will be already no longer send Reports to date:';
$langs['insert_error1'] = 'Error on insert Data into the Blocklist';
$langs['insert_norelay'] = 'The Abuse-Address is not in relationship with the IP';
$langs['insert_ipexists'] = 'IP is already in our database. Please edit your Server-Profile.';
$langs['insert_emailexists'] = '<strong>Die E-Mailadresse existiert bereits. Angriffe werden daher <u>NUR</u> beim ersten Server gez&auml;hlt</strong>. Checkbox aktivieren und noch mals senden!';
$langs['insert_retry'] = 'JA, trotz gleicher Absender-Adresse eintragen.';
$langs['insert_retry2'] = 'JA, trotz gleicher IP-Adresse eintragen.';
$langs['insert_notyours'] = 'This server is not associated with your account. (you silly Hacker *g*)';
$langs['insert_tolate'] = 'We have no Attacks from this IP from the last 14 Days. Too old';
$langs['login_subject'] = 'User-Login to your Server-Management';
$langs['login_email1'] = '??????????, ??????? ??? e-mail!';
$langs['login_email2'] = 'Your e-mail is to <strong>long</strong> (max. 100 Sign)!';
$langs['login_email3'] = 'E-Mailaddress or Password wrong!';
$langs['login_registerres1'] = 'It still runs a registry with this name (max. 7 days)';
$langs['login_registerres2'] = 'Resend registration mail';
$langs['login_nofound'] = 'No Username/E-Mail found for the data!';
$langs['login_emailblocked'] = 'The E-Mailaddress/Username was blocked.';
$langs['login_offline'] = 'Your Account is offline, because your Address is false or other stuff:';
$langs['login_blocked'] = 'Your Account is blocked/offline; Reason:';
$langs['register_subject'] = 'Cr&amp;eacute;ez un compte pour les rapports.';
$langs['register_confirm'] = 'Lien de confirmation de l\'enregistrement d\'un compte sur blocklist.de';
$langs['register_complete'] = 'Registration complete, your Login-Data for www.blocklist.de';
$langs['register_allparams'] = 'Please call the link with all parameters, or let you resend the Confirmation-Mail.';
$langs['register_name3'] = 'Ce nom d\'utilisateur existe d&amp;eacute;j&amp;agrave; ou a &amp;eacute;t&amp;eacute; bloqu&amp;eacute;. Merci d\'utiliser un autre nom.';
$langs['register_name4'] = 'Une inscription avec ce nom est d&amp;eacute;j&amp;agrave; en cours.';
$langs['register_resend'] = 'Renvoyer le mail d\'inscription';
$langs['register_emailfound'] = 'Cette adresse est d&amp;eacute;j&amp;agrave; utilis&amp;eacute;e.';
$langs['register_toold'] = 'Votre lien a plus de 7 jours. Merci de cr&amp;eacute;er une nouvelle inscription.';
$langs['register_noactive'] = 'Nous ne pouvons pas activer votre compte. Merci de nous contacter avec votre adresse email.';
$langs['register_agb'] = 'Please accept the <a href=&quot;http://www.blocklist.de/de/terms.html&quot; title=&quot;Terms and private policy&quot; target=&quot;_blank&quot;>Terms</a>!';
$langs['disable_subject'] = 'Blocking your E-Mailaddress on www.blocklist.de';
$langs['resend_subject'] = 'Confirmation Mail from blocklist.de (again)';
$langs['resend_tomuch'] = 'D&amp;eacute;sol&amp;eacute;, mais nous avons d&amp;eacute;j&amp;agrave; envoy&amp;eacute; un mail de confirmation dans les derni&amp;egrave;res minutes. Merci de r&amp;eacute;essayer plus tard.';
$langs['resend_nouser'] = 'Ce nom d\'utilisateur n\'existe pas.';
$langs['resend_noregister'] = 'There is no Registration process with the name/address.';
$langs['resend_regkey'] = 'Merci d\'ins&amp;eacute;rer la RegKey.';
$langs['resend_regkey2'] = 'The RegKey may only contain numbers.';
$langs['data_currentpwd'] = 'Entrez votre more de passe actuel.';
$langs['data_currentpwd2'] = 'Your current Password is incorrect!';
$langs['data_newpwd'] = 'Vkl?d?n? nov&amp;eacute; heslo prosim!';
$langs['data_newpwd2'] = '??? ????? ?????? ?????? ???? ??????? 8 ????????';
$langs['data_newpwd3'] = 'Confirmez votre nouveau mot de passe &amp;agrave; nouveau.';
$langs['data_newpwd4'] = 'Your new Password does not match.';
$langs['data_sucess'] = '??????? ????????.';
$langs['server_add'] = 'Ajouter un nouveau serveur';
$langs['server_nums'] = 'Currently, you have entered {TEXTHALTER} Server.';
$langs['server_sucess'] = 'Votre serveur a &amp;eacute;t&amp;eacute; enregistr&amp;eacute; / supprim&amp;eacute; avec succ&amp;egrave;s.';
$langs['server_notyours'] = 'We could not found any Server with the Server-ID to your Customer-ID!';
$langs['server_edit'] = 'Modifier votre serveur &quot;{TEXTHALTER}&quot;.';
$langs['server_delete'] = 'Supprimer votre serveur &quot;{TEXTHALTER}&quot;.';
$langs['server_list'] = 'Afficher attaques sur votre serveur &quot;{TEXTHALTER}&quot;.';
$langs['server_ids'] = 'Please add your SERVER-ID into the Request.';
$langs['server_timezone'] = 'Please choose the timezone which is set on you server.';
$langs['server_usetime'] = 'Vybrat ?asov? z?na z server prosim.';
$langs['server_settimezone'] = 'Merci de modifier votre serveur et de configurer un fuseau horaire.';
$langs['server_contact'] = 'Bitte kontaktieren Sie uns, wir haben den Server bei uns deaktiviert.';
$langs['server_ip6'] = 'Dies ist keine korrekte IPv6-Adresse.';
$langs['password_confirm'] = 'Confirmation link for a new password on blocklist.de';
$langs['password_name1'] = 'S\'il vous pla&amp;icirc;t entrer votre nom d\'utilisateur.';
$langs['password_name2'] = 'Your Username is too <strong>long</strong> (max. 100 characters)!';
$langs['password_name3'] = 'Your Username is <strong>invalid</strong> (min. 3, max. 100 characters)!';
$langs['password_nofound'] = 'The address does not match the name.';
$langs['password_allparams'] = 'This verification link is invalid. Please use a valid link, or request a new one.';
$langs['password_nofound2'] = 'Unfortunately, no requirement to find a password with the given parameters.';
$langs['password_toold'] = 'Unfortunately, the email verification request has expired. Please register again to receive a new confirmation link and remember to verify it within 12 hours.';
$langs['password_regkey'] = 'Unfortunately it is the passed RegKey not match the registered.';
$langs['password_nofound3'] = 'Unfortunately, other parameters of the link to vote is not in accordance with the stored data';
$langs['password_allready'] = 'This verification link was already used on {TEXTHALTER}.';
$langs['password_allready2'] = 'This verification link was already used on {TEXTHALTER} and the Address blocked/activated.';
$langs['password_errorid'] = 'Failed to update the data. Please contact our support with the <strong>ID: {TEXTHALTER}</strong>';
$langs['password_erroractive'] = 'Failed to activate the new password. Please get in touch with our support.';
$langs['password_success'] = 'Your new password for your account on blocklist.de';
$langs['replace_hacked'] = 'La case a &amp;eacute;t&amp;eacute; compromise.';
$langs['replace_notyou'] = 'The entry doesn\'t belong to your user.';
$langs['replace_notdel'] = 'L\'entr&amp;eacute;e s&amp;eacute;lectionn&amp;eacute;e ne peut pas &amp;ecirc;tre supprim&amp;eacute;e.';
$langs['replace_notempty'] = 'Content must not be empty or contain spaces.';
$langs['replace_tolong'] = 'Value must be no larger than 255 characters!';
$langs['replace_tosmal'] = 'Value must be longer than 3 characters!';
$langs['replace_saved'] = 'Param&amp;egrave;tres enregistr&amp;eacute;s avec succ&amp;egrave;s.';
$langs['replace_error'] = 'Erreur : l\'entr&amp;eacute;e ne peut pas &amp;ecirc;tre enregistr&amp;eacute;e.';
$langs['whitelist_hacked'] = 'La case a &amp;eacute;t&amp;eacute; compromise.';
$langs['whitelist_notyou'] = 'The Entry doesn\'t belong to your user.';
$langs['whitelist_notdel'] = 'Couldn\'t delete the entry.';
$langs['whitelist_notempty'] = 'Contenu ne peut &amp;ecirc;tre vide ou contenir des espaces.';
$langs['whitelist_tolong'] = 'Value must be no larger than 255 characters!';
$langs['whitelist_tosmal'] = 'Value must be longer than 3 characters!';
$langs['whitelist_saved'] = '????????? ??????? ?????????.';
$langs['whitelist_error'] = 'Erreur : Les param&amp;egrave;tres ne peuvent pas &amp;ecirc;tre enregistr&amp;eacute;s.';
$langs['delete_confirm'] = 'Confirmation link to delete your account';
$langs['delist_sucess'] = 'IP marked as fixed and cleaned and deleted from the download-list (in the next 10 Minutes).';
$langs['delist_error'] = 'Desv?rre kunne vi ikke gemme posten.';
$langs['delist_errors'] = 'Der opstod en fejl.';
$langs['delist_already'] = 'IP er fjernet fra download liste.';
$langs['delist_notfound'] = '?????? ??? ??????? IP-?????? ?? ???????';
$langs['profil_logout'] = 'Byli jste ?sp?n? odhl?eni.';
$langs['profil_apikey'] = 'Merci de sauvegarder votre profile, votre cl&amp;eacute; API n\'est pas enregistr&amp;eacute;e.';
$langs['session_notloged'] = 'Vous n\'&amp;ecirc;tes pas identifi&amp;eacute;!';
$langs['session_pleaselogin'] = 'Vous n\'&amp;ecirc;tes pas identifi&amp;eacute;. Merci de vous connecter!';
$langs['session_tooold'] = 'Vous avez &amp;eacute;t&amp;eacute; inactif trop longtemps - merci de vous identifier &amp;agrave; nouveau!';
$langs['session_nopermissions'] = 'Vous n\'avez pas le droit de voir ce site!';
$langs['session_already'] = 'Vous &amp;ecirc;tes d&amp;eacute;j&amp;agrave; connect&amp;eacute;!';
$langs['pleasechange'] = 'Please change your password so that it can be saved with a new salting and hashing method we recently implemented. That new salting and hashing method is more dynamic and stronger.';
$langs['httpapi_noserver'] = 'Please insert the Server-E-Mailaddress or Server-ID.';
$langs['httpapi_notvalidserver'] = 'Server-E-Mailaddress is not correct.';
$langs['httpapi_noapikey'] = 'Please insert the API-Key from the Server.';
$langs['httpapi_logs'] = 'Please insert the Logfiles, and more than 20 Signs.';
$langs['httpapi_ip'] = 'Please insert the Attacker-IP or the IP is invalid.';
$langs['httpapi_serverunknown'] = 'Error on the Server-Data, false e-mailaddress, false server-id....?';
$langs['httpapi_senderapi'] = 'The API-Key is not the Api-Key from the Server.';
$langs['httpapi_reported10'] = 'IP-Address is already reported from your Server in the last 10 Minutes.';
$langs['httpapi_noservice'] = 'Please choose the impugned service.';
$langs['httpapi_serverempty'] = 'Please add your Server-ID or Server-From-Address.';
$langs['httpapi_help'] = '
        <h2>English:</h2><br />
    Call: <strong>http://www.blocklist.de/en/httpreports.html?</strong>
    <br />
    <h3>required Variables:</h3>
    <br />
        <strong>email</strong>: string (E-Mailaddress from Server or ID)
        <br />
        <strong>apikey: </strong> string (in your Profil under SERVER)
        <br />
        <strong>ip</strong>: string (ipv4/ipv6 Address) (Attacker)
        <br />
        <strong>service: </strong> string (Service which was attacked (ssh, imap, ftp...))
        <br />
        <strong>logs</strong>: text (Logfiles)
                <br />
                <strong>format</strong>: text, json, php, xml (Error-Message/OK-Message/Return-Values format)
<br />
<br />
    Version 0.0.0.1

';
$langs['utitle_home'] = 'What is www.BlockList.de?';
$langs['utitle_search'] = 'Search for IP or AS-numbers on blocklist.de';
$langs['utitle_contact'] = 'Contact us about Questions, Whishes, Bugs...';
$langs['utitle_contact_sent'] = 'Message successfully sent';
$langs['utitle_searchresult'] = 'Search-Result for IP or AS-numbers';
$langs['utitle_partners'] = 'Partners/Sponsors from www.blocklist.de';
$langs['utitle_statistics'] = 'Statistics about reported Attacks';
$langs['utitle_statisticsmonth'] = 'Statistics for the current month';
$langs['utitle_statisticsgraph'] = 'Graphical Statistics';
$langs['utitle_graph'] = 'Graphical Statistics';
$langs['utitle_insert'] = 'Stop Reports for 7 Days';
$langs['utitle_login'] = 'Login to your Profile';
$langs['utitle_register'] = 'title_register';
$langs['utitle_register1'] = 'title_register1';
$langs['utitle_registere'] = 'title_register2';
$langs['utitle_resend'] = 'Resend the Confirmation-Mail again';
$langs['utitle_delist'] = 'Remove IP earlier from list';
$langs['utitle_api'] = 'API/RBL/DNS from www.blocklist.de';
$langs['utitle_rbldns'] = 'Using blocklist over DNS/RBL faster';
$langs['utitle_downloads'] = 'Our Reporting-Tool and other Downloads';
$langs['utitle_httpreports'] = 'Reports Attacker over GET-/POST-Requests';
$langs['utitle_export'] = 'Export all blocked IPs';
$langs['utitle_imprint'] = 'Imprint from www.blocklist.de';
$langs['utitle_userlogin'] = 'Login into your Profile';
$langs['utitle_terms'] = 'Our Terms and Privacy Policy';
$langs['utitle_register.resend'] = 'Resend the Confirmation-Mail';
$langs['utitle_register.confirm'] = 'Registration Step 2 from 2';
$langs['utitle_register.block'] = 'Registration step 2 from 2 (blocing)';
$langs['utitle_password'] = 'Create a new password';
$langs['utitle_view'] = 'View Attacks from the IP: ip ';
$langs['utitle_xarf-validator'] = 'X-ARF Validator';
$langs['utitle_xarf-validator-report'] = 'X-ARF Validator for the Yaml-Reports';
$langs['utitle_profile_replace'] = 'Replace Data from your Reports';
$langs['utitle_profile_index'] = 'Server-Management/Profile';
$langs['utitle_profile_server'] = 'Your active Server';
$langs['utitle_profile_server.edit'] = 'Add/edit your Server';
$langs['utitle_profile_server.delete'] = 'Delete a Server';
$langs['utitle_profile_whitelist'] = 'IP Whitelist';
$langs['utitle_profile_statistics'] = 'Server Statistics (Own Server)';
$langs['utitle_profile_change'] = 'Change your Profile/Settings';
$langs['utitle_profile_delete'] = 'Delete your Account';
$langs['utitle_profile_reports'] = 'daily-/weekly-/monthly- summery Reports.';
$langs['utitle_profile_server.list'] = 'Result for the Server {$serverid} Counts: {$maxcounts} complete time';
$langs['utitle_profile_allstats'] = 'Graphical Statistics all Users';
$langs['utitle_logout'] = 'You have been logged out.';
$langs['utitle_profile_logout'] = 'You have been logged out.';
$langs['title_profile'] = 'Your Login/Profile on blocklist.de';
$langs['utitle_profile'] = 'title_profile';
$langs['utitle_error'] = 'Error: automatically logout';
$langs['export_all'] = 'Toutes les adresses IP ayant attaqu&amp;eacute;es un de vos serveurs dans les 48 derni&amp;egrave;res heures.';
$langs['export_ssh'] = 'Toutes les adresses IP nous ayant &amp;eacute;t&amp;eacute; rapport&amp;eacute; comme ayant attaqu&amp;eacute;es le service SSH.';
$langs['export_mail'] = 'Toutes les IP qui ont &amp;eacute;t&amp;eacute; remont&amp;eacute;es ces 48 derni&amp;egrave;res heures suite &amp;agrave; des attaques sur les serveurs mails, Postfix ...';
$langs['export_apache'] = 'Toutes les IP qui ont &amp;eacute;t&amp;eacute; remont&amp;eacute;es dans les 48 derni&amp;egrave;res heures suite &amp;agrave; des attaques sur le service Apache, Apache-DDOS, RFI-Attacks ...';
$langs['export_bots'] = 'Toutes les adresses IP qui ont &amp;eacute;t&amp;eacute; report&amp;eacute;es durant les derni&amp;egrave;res 48 heures ont g&amp;eacute;n&amp;eacute;r&amp;eacute;es des attaques RFI-Attacks, REG-Bots, IRC-Bots or BadBots (BadBots = spam post&amp;eacute; sur un forum ou un wiki ouvert; Reg-Bots = s\'est enregistr&amp;eacute;).';
$langs['export_imap'] = 'All IP addresses which have been reported within the last 48 hours for attacks on the Service imap, sasl, pop3.....';
$langs['export_ftp'] = 'All IP addresses which have been reported within the last 48 hours for attacks on the Service FTP.';
$langs['export_asterisk'] = 'All IP addresses that tried to login in a SIP-, VOIP- or Asterisk-Server and are inclueded in the IPs-List from <a href=&quot;https://twitter.com/#!/voipabuse&quot; title=&quot;http://www.infiltrated.net/&quot;>http://www.infiltrated.net/</a> (Twitter).';
$langs['title_trylater'] = '&amp;Agrave; venir. S\'il vous pla&amp;icirc;t attendre quelques jours';
$langs['title_rbldns'] = 'Use the IP-List over DNS (RBLDNS) to block IPs faster';
$langs['title_httpreports'] = 'Report Attacks over GET-/POST-Request to blocklist.de without Fail2Ban or Mail';
$langs['contact'] = 'typS&amp;eacute;lectionnez un sujet svp.';
$langs['data'] = 'sucessDaten wurden erfolgreich Aktualisiert.';
$langs['delete'] = 'confirmBest?tigungslink zum l?schen Ihres Accounts';
$langs['delist'] = 'sucessIP erfolgreich als gefixt markiert und aus der Liste (Download) entfernt (in den n&auml;chsten 10 Minuten).';
$langs['disable'] = 'subjectE-Mailadresse auf www.blocklist.de gesperrt.';
$langs['error'] = 'systemDie &uuml;bergebenen Daten stimmen nicht mit unserem System &uuml;berein.';
$langs['insert'] = 'tolateEs ist kein Angriff mehr f&uuml;r die IP gespeichert..... l&auml;nger als 14 Tage her?';
$langs['login'] = 'subjectUser-Login zu Ihrer Server-Verwaltung';
$langs['password'] = 'tooldDer Link wurde leider nicht innerhalb von 12 Stunden best&auml;tigt. Bitte erstellen Sie sich einen neuen.';
$langs['profil'] = 'logoutVous avez &amp;eacute;t&amp;eacute; d&amp;eacute;connect&amp;eacute;.';
$langs['register'] = 'tooldVotre lien a plus de 7 jours. Merci de cr&amp;eacute;er une nouvelle inscription.';
$langs['replace'] = 'tosmalWert muss l&auml;nger als 3 Zeichen sein!';
$langs['resend'] = 'tomuchD&amp;eacute;sol&amp;eacute;, mais nous avons d&amp;eacute;j&amp;agrave; envoy&amp;eacute; un mail de confirmation dans les derni&amp;egrave;res minutes. Merci de r&amp;eacute;essayer plus tard.';
$langs['search'] = 'takealookBitte pr&uuml;fen Sie auch die Liste von <a href=&quot;http://honeystats.info/glastopf_rbldnsd.zone&quot; title=&quot;Honeystats.info RFI-Attacks&quot;>http://honeystats.info/</a>, wenn die Suche kein Ergebnis zuruecklieferte.';
$langs['server'] = 'usetimeBitte Zeitzone vom Server ausw&auml;hlen.';
$langs['session'] = 'toooldVous avez &amp;eacute;t&amp;eacute; inactif trop longtemps - merci de vous identifier &amp;agrave; nouveau!';
$langs['title'] = 'httpapiIP de l\'attaquant Rapport adresses via http (GET/POST).';
$langs['whitelist'] = 'tosmalWert muss l&auml;nger als 3 Zeichen sein!';