<?php

$langs['title_export'] = 'www.blocklist.de -- Exporter tous les Attacker-IP &#224; partir des 48 derni&#200;res heures.';
$langs['title_home'] = 'www.blocklist.de -- Fail2Ban-Service Reporting (nous envoyer des rapports d\'attaques sur Postfix, SSH, Apache-attaques, Spam Bots, irc-Bots, Reg-Bots, DDos et plus) de Fail2Ban via X-ARF';
$langs['title_index'] = $langs['title_home'];
$langs['title_contact'] = 'Formulaire de contact, demandez-nous ou envoyez-nous votre serveur de donn&#233;es pour envoyer Rapport sur nous.';
$langs['title_partners'] = 'www.blocklist.de -- nos partenaires, qui nous envoient Fail2ban-Reports';
$langs['title_statistics'] = 'www.blocklist.de -- Statistiques concernant les derni&#232;res attaques des IP, ET, Pays .... et plus';
$langs['title_statisticsmonth'] = 'Statistiques concernant les attaques &#224; partir de seulement le mois en cours (IPs, ASN, pays ...)';
$langs['title_graph'] = 'Statistiques graphiques sur nos attaques (dont Service) et r&#233;sumer nos rapports';
$langs['title_insert'] = 'www.blocklist.de -- Arr&#234;tez les rapports pour une adresse IP et E-Mail-Adresse pour 7 Jours pour r&#233;soudre le probl&#232;me';
$langs['title_servergraph'] = 'Statistiques graphiques sur les attaques sur les serveurs individuels';
$langs['title_login'] = 'Connectez-vous &#224; votre compte sur www.blocklist.de';
$langs['title_register'] = 'Cr&amp;eacute;er un compte sur www.blocklist.de';
$langs['title_register1'] = 'Confirmer votre inscription sur www.blocklist.fr';
$langs['title_register2'] = 'Blocage des adresses &#233;lectroniques pour l\'inscription sur www.blocklist.de';
$langs['title_resend'] = 'Renvoyer le mail de confirmation de blocklist.de';
$langs['title_password'] = 'Cr&amp;eacute;er un nouveau mot de passe pour votre compte sur blocklist.de.';
$langs['title_replace'] = 'www.blocklist.de -- Remplacer automatiquement les donn&#233;es de vos rapports';
$langs['title_whitelist'] = 'Ajouter votre adresse IP &amp;agrave; la liste blanche de blocklist.de';
$langs['title_downloads'] = 'T&#233;l&#233;charger nos rapports-Scripts pour envoyer vos rapports d\'auto (en cours)';
$langs['title_allstats'] = 'www.blocklist.de -- Tout utilisateur sur un statistique pour la comparaison';
$langs['title_data'] = 'Modifiez votre profil/param&#232;tres';
$langs['title_profil'] = 'www.blocklist.de -- Votre client Login pour votre compte sur blocklist.de';
$langs['title_server'] = 'Votre serveurs enregistr&amp;eacute; sur blocklist.de';
$langs['title_serverstats'] = 'Statistiques graphiques sur les attaques sur votre serveurs.';
$langs['title_imprint'] = 'Imprim&amp;eacute; depuis www.blocklist.de';
$langs['title_terms'] = 'Conditions G&#233;n&#233;rales et Politique de confidentialit&#233; pour un compte sur blocklist.de';
$langs['title_delete'] = 'Supprimer votre compte de www.blocklist.de';
$langs['title_list'] = 'Afficher les attaques sur votre serveur';
$langs['title_api'] = 'API de www.blocklist.de. Afficher Server- ou tout utilisateur Statistiques pour vos propres Page d\'accueil/Scripts';
$langs['title_reports'] = 'Rapports sommaires des attaques et des rapports &#224; partir de votre serveur';
$langs['title_delist'] = 'Supprimer votre adresse IP dans la liste des 24 heures plus t&#212;t';
$langs['title_httpapi'] = 'adresses/de l\'attaquant via http Rapport IP (GET/POST)';
$langs['error_one'] = 'Il y avait une erreur.';
$langs['error_more'] = 'Plusieurs erreurs se sont produites.';
$langs['error_db'] = 'Impossible de saisir les donn&#233;es dans la base de donn&#233;es. Veuillez r&#233;essayer!';
$langs['error_system'] = 'Malheureusement, les données fournies ne sont pas d\'accord avec le syst&#232;me';
$langs['error_mail'] = 'D&#233;sol&#233;, ne pouvait pas se connecter au serveur de messagerie. Veuillez r&#233;essayer';
$langs['contact_typ'] = 'S&amp;eacute;lectionnez un sujet svp.';
$langs['contact_mitteilung1'] = 'Ins&amp;eacute;rez votre question ou vos donn&amp;eacute;es.';
$langs['contact_mitteilung2'] = 'Utilisez plus de 15 signes, s\'il-vous-plait!';
$langs['contact_sender1'] = 'Entrez votre adresse d\'exp&amp;eacute;diteur Fail2Ban (adresse de retour configur&amp;eacute;e dans jail.conf).';
$langs['contact_sender2'] = 'Votre adresse est invalide (valide : mailbox@domain.tld)';
$langs['contact_daten'] = 'S\'il vous pla&amp;icirc;t entrez votre IP de l\'exp&amp;eacute;diteur!';
$langs['contact_display'] = 'S\'il vous pla&amp;icirc;t entrer votre nom d\'affichage!';
$langs['contact_email1'] = 'S\'il vous pla&amp;icirc;t entrer votre adresse e-mail pour les r&amp;eacute;ponses.';
$langs['contact_email2'] = $langs['contact_sender2'];
$langs['contact_server'] = 'S\'il vous plaît insérer le montant de serveurs que vous avez';
$langs['contact_error'] = 'Erreur ! V&amp;eacute;rifiez vos donn&amp;eacute;es.';
$langs['contact_noip'] = 'L\'adresse IP n\'est pas au format IPv4 ou IPv6';
$langs['contact_noja'] = 'S\'il vous pla&amp;icirc;t confirmez avec &quot;JA&quot;.';
$langs['contact_noja2'] = 'S\'il vous pla&#206;t ins&#233;rer exacte JA';
$langs['contact_rid'] = 'Le RID doit &#234;tre uniquement num&#233;rique';
$langs['search_counterreset'] = '<small>(ce mois-ci)</small>';
$langs['search_counterreset2'] = '<small>(temps complet)</small>';
$langs['search_ip'] = 'S\'il vous pla&#238;t ins&#233;rer une adresse IP ou un num&#233;ro AS';
$langs['search_nofound'] = 'Aucun r&amp;eacute;sultat pour cette recherche';
$langs['search_as'] = 'S\'il vous pla&amp;icirc;t Entrez un num&amp;eacute;ro AS';
$langs['search_notuse'] = 'au repos';
$langs['search_noipv4'] = 'Votre IP n\'est pas correcte (ipV4 uniquement).';
$langs['search_takealook'] = 'S\'il vous plaît aussi jeter un oeil à la <a href="http://honeystats.info/glastopf_rbldnsd.zone" title="Honeystats.info RFI-Attacks">http://honeystats.info/</a> si votre recherche Pas de correspondance.';
$langs['insert_email'] = 'S\'il vous pla&#238;t ins&#233;rer un abus adresse';
$langs['insert_emailnotyour'] = 'L\'adresse est d&#233;ja utilis&#233;e par un autre utilisateur';

$langs['insert_ok1'] = 'Pour l\'IP sera jamais envoyer des rapports déjà à ce jour:';
$langs['insert_ok2'] = 'Pour l\'IP et les abus-Address nous n\'envoyons pas plus maintenant des rapports à ce jour:';
$langs['insert_ok3'] = 'Pour l\'IP et l\'abus-Adresse est déjà plus envoyer des rapports à ce jour:';
$langs['insert_error1'] = 'Erreur sur les données d\'insertion dans le Blocklist';
$langs['insert_norelay'] = 'L\'abus-Adresse est pas en relation avec l\'IP';
$langs['insert_ipexists'] = 'IP est déjà dans notre base de données. S\'il vous plaît modifier votre serveur Profil.';
$langs['insert_emailexists'] = '<strong>L\'adresse e-mail existe déjà. Les attaques sont donc <u>ONLY</u> pour la première sgd serveur &auml;hlt </strong>. Case Activer et encore une fois envoyer!';
$langs['insert_retry'] = 'OUI, Entrez en dépit de la même adresse de retour.';
$langs['insert_retry2'] = 'OUI, entrez malgré la même adresse IP.';
$langs['insert_notyours'] = 'son serveur est pas associé à votre compte. (Vous silly Hacker *g*)';
$langs['insert_tolate'] = 'Nous avons pas les attaques de cette adresse IP à partir des 14 derniers jours. Trop vieux';
$langs['login_subject'] = 'Utilisateur Connectez-vous pour la gestion de votre serveur';
$langs['login_email1'] = 'S\'il vous plaît insérer votre adresse e-mail!';
$langs['login_email2'] = 'Votre e-mail est de <strong>longue</strong> (max. 100 Sign)!';
$langs['login_email3'] = 'Adresse e-mail ou mot de passe mal!';
$langs['login_registerres1'] = 'It still runs a registry with this name (max. 7 days)';
$langs['login_registerres2'] = 'Renvoyer inscription email';
$langs['login_nofound'] = 'Aucun nom d\'utilisateur/EMail trouvé pour les données!';
$langs['login_emailblocked'] = 'L\'adresse e-mail/Nom d\'utilisateur a été bloqué.';
$langs['login_offline'] = 'Votre compte est déconnecté, parce que votre adresse est fausse ou d\'autres choses:';
$langs['login_blocked'] = 'Votre compte est bloqué/hors ligne; Raison:';
$langs['register_subject'] = 'Cr&amp;eacute;ez un compte pour les rapports.';
$langs['register_confirm'] = 'Lien de confirmation de l\'enregistrement d\'un compte sur blocklist.de';
$langs['register_allparams'] = 'S\'il vous plaît appelez le lien sur tous les paramètres, ou laisser le resend confirmation par e-mail.';
$langs['register_complete'] = 'L\'enregistrement est terminé, les informations de connexion de votre compte à blocklist.de';
$langs['register_confirm'] = 'Lien de confirmation de l\'enregistrement d\'un compte sur blocklist.de';
$langs['register_name3'] = 'Ce nom d\'utilisateur existe d&amp;eacute;j&amp;agrave; ou a &amp;eacute;t&amp;eacute; bloqu&amp;eacute;. Merci d\'utiliser un autre nom.';
$langs['register_name4'] = 'Une inscription avec ce nom est d&amp;eacute;j&amp;agrave; en cours.';
$langs['register_resend'] = 'Renvoyer le mail d\'inscription';
$langs['register_emailfound'] = 'Cette adresse est d&amp;eacute;j&amp;agrave; utilis&amp;eacute;e.';
$langs['register_toold'] = 'Votre lien a plus de 7 jours. Merci de cr&amp;eacute;er une nouvelle inscription.';
$langs['register_noactive'] = 'Nous ne pouvons pas activer votre compte. Merci de nous contacter avec votre adresse email.';
$langs['register_agb'] = 'S\'il vous plaît accepter la <a href=&quot;https://www.blocklist.de/fr/terms.html&quot; title=&quot;Terms and privacy policy&quot; target=&quot;_blank&quot;>Termes</a>!';
$langs['disable_subject'] = 'Blocage votre adresse email sur www.blocklist.de';
$langs['resend_subject'] = 'Confirmation Mail à partir blocklist.de (nouveau)';
$langs['resend_tomuch'] = 'D&amp;eacute;sol&amp;eacute;, mais nous avons d&amp;eacute;j&amp;agrave; envoy&amp;eacute; un mail de confirmation dans les derni&amp;egrave;res minutes. Merci de r&amp;eacute;essayer plus tard.';
$langs['resend_nouser'] = 'Ce nom d\'utilisateur n\'existe pas.';
$langs['resend_noregister'] = 'There is no Registration process with the name/address.';
$langs['resend_regkey'] = 'Merci d\'ins&amp;eacute;rer la RegKey.';
$langs['resend_regkey2'] = 'La clé Reg-Key ne peut contenir que des chiffres..';
$langs['data_currentpwd'] = 'Entrez votre more de passe actuel.';
$langs['data_currentpwd2'] = 'Votre mot de passe actuel est incorrect!';
$langs['data_newpwd'] = 'S\'il vous plaît insérer votre nouveau mot de passe.';
$langs['data_newpwd2'] = 'Votre nouveau mot de passe doit avoir plus de 8 caractères.';
$langs['data_newpwd3'] = 'Confirmez votre nouveau mot de passe &amp;agrave; nouveau.';
$langs['data_newpwd4'] = 'Votre nouveau mot de passe ne correspond pas.';
$langs['data_sucess'] = 'Votre profil a été mis à jour.';
$langs['server_add'] = 'Ajouter un nouveau serveur';
$langs['server_nums'] = 'Actuellement, vous avez entré {TEXTHALTER} Serveur.';
$langs['server_sucess'] = 'Votre serveur a &amp;eacute;t&amp;eacute; enregistr&amp;eacute;/supprim&amp;eacute; avec succ&amp;egrave;s.';
$langs['server_notyours'] = 'Nous ne pouvions pas trouvé de serveur avec le serveur-ID à votre client-ID!';
$langs['server_edit'] = 'Modifier votre serveur &quot;{TEXTHALTER}&quot;.';
$langs['server_delete'] = 'Supprimer votre serveur &quot;{TEXTHALTER}&quot;.';
$langs['server_list'] = 'Afficher attaques sur votre serveur &quot;{TEXTHALTER}&quot;.';
$langs['server_ids'] = 'S\'il vous plaît ajouter votre SERVER-ID dans la demande.';
$langs['server_timezone'] = 'S\'il vous plaît choisir le fuseau horaire qui est fixé sur votre serveur.';
$langs['server_usetime'] = 'S\'il vous plaît choisir le fuseau horaire de votre serveur.';
$langs['server_settimezone'] = 'Merci de modifier votre serveur et de configurer un fuseau horaire.';
$langs['server_contact'] = 'S\'il vous plaît contactez-nous, nous avons désactivé le serveur avec nous.';
$langs['server_ip6'] = 'Ce n\'est pas une adresse IPv6 appropriée.';
$langs['password_confirm'] = 'lien de confirmation pour un nouveau mot de passe blocklist.de';
$langs['password_name1'] = 'S\'il vous pla&amp;icirc;t entrer votre nom d\'utilisateur.';
$langs['password_name2'] = 'Votre nom d\'utilisateur est trop <strong>longue</strong> (max. 100 caractères)!';
$langs['password_name3'] = 'Votre nom d\'utilisateur est <strong>non valide</strong> (min. 3, max. 100 caractères)!';
$langs['password_nofound'] = 'L\'adresse ne correspond pas au nom.';
$langs['password_allparams'] = 'Ce lien de vérification est invalide. S\'il vous plaît utiliser un lien valide, ou en demander un nouveau.';
$langs['password_nofound2'] = 'Malheureusement, aucune exigence de trouver un mot de passe avec les paramètres donnés.';
$langs['password_toold'] = 'Malheureusement, la demande de vérification de courrier électronique a expiré. S\'il vous plaît vous inscrire à nouveau pour recevoir un nouveau lien de confirmation et rappelez-vous de le vérifier dans les 12 heures.';
$langs['password_regkey'] = 'Malheureusement, il est la clé Reg passé ne correspond l\'enregistrement.';
$langs['password_nofound3'] = 'Malheureusement, d\'autres paramètres du lien vers vote ne sont pas en conformité avec les données stockées';
$langs['password_allready'] = 'Ce lien de vérification a déjà été utilisé sur {TEXTHALTER}.';
$langs['password_allready2'] = 'Ce lien de vérification a déjà été utilisé sur {TEXTHALTER} et l\'adresse bloqué/activée.';
$langs['password_errorid'] = 'Impossible de mettre à jour les données. S\'il vous plaît contacter notre support à la <strong>ID: {TEXTHALTER}</strong>';
$langs['password_erroractive'] = 'Impossible d\'activer le nouveau mot de passe. S\'il vous plaît entrer en contact avec notre soutien.';
$langs['password_success'] = 'Votre nouveau mot de passe pour votre compte sur blocklist.de';
$langs['replace_hacked'] = 'La case a &amp;eacute;t&amp;eacute; compromise.';
$langs['replace_notyou'] = 'L\'entr&#233;e ne fait pas partie de votre utilisateur.';
$langs['replace_notdel'] = 'L\'entr&amp;eacute;e s&amp;eacute;lectionn&amp;eacute;e ne peut pas &amp;ecirc;tre supprim&amp;eacute;e.';
$langs['replace_notempty'] = 'Contenu ne doit pas être vide ou contenir des espaces.';
$langs['replace_tolong'] = 'La valeur doit pas être supérieure à 255 caractères!';
$langs['replace_tosmal'] = 'La valeur doit être plus de 3 caractères!';
$langs['replace_saved'] = 'Param&amp;egrave;tres enregistr&amp;eacute;s avec succ&amp;egrave;s.';
$langs['replace_error'] = 'Erreur : l\'entr&amp;eacute;e ne peut pas &amp;ecirc;tre enregistr&amp;eacute;e.';
$langs['whitelist_hacked'] = 'La case a &amp;eacute;t&amp;eacute; compromise.';
$langs['whitelist_notyou'] = 'L\'entr&#233;e ne fait pas partie de votre utilisateur.';
$langs['whitelist_notdel'] = 'Impossible de supprimer l\'entr&#233;e.';
$langs['whitelist_notempty'] = 'Contenu ne peut &amp;ecirc;tre vide ou contenir des espaces.';
$langs['whitelist_tolong'] = 'La valeur doit pas &#234;tre sup&#233;rieure &#224; 255 caract&#232;res!';
$langs['whitelist_tosmal'] = 'La valeur doit &#234;tre plus de 3 caract&#232;res!';
$langs['whitelist_saved'] = 'Param&#232;tres sauvegardés avec succ&#232;s.';
$langs['whitelist_error'] = 'Erreur : Les param&amp;egrave;tres ne peuvent pas &amp;ecirc;tre enregistr&amp;eacute;s.';
$langs['delete_confirm'] = 'lien de confirmation pour supprimer votre compte';
$langs['delist_sucess'] = 'marqué IP comme fixe et nettoyé et supprimé de la liste download (dans les 10 prochaines minutes).';
$langs['delist_error'] = 'D&amp;eacute;sol&amp;eacute;, les donn&amp;eacute;es n\'ont pas pu &amp;ecirc;tre sauvegard&amp;eacute;';
$langs['delist_errors'] = 'Une erreur est survenue:';
$langs['delist_already'] = 'Cette IP a d&amp;eacute;j&amp;agrave; &amp;eacute;t&amp;eacute; supprim&amp;eacute;e de la liste.';
$langs['delist_notfound'] = 'Il n\'y a aucun r&amp;eacute;sultat pour cette IP.';
$langs['profil_logout'] = 'Vous avez &amp;eacute;t&amp;eacute; d&amp;eacute;connect&amp;eacute;.';
$langs['profil_apikey'] = 'Merci de sauvegarder votre profile, votre cl&amp;eacute; API n\'est pas enregistr&amp;eacute;e.';
$langs['session_notloged'] = 'Vous n\'&amp;ecirc;tes pas identifi&amp;eacute;!';
$langs['session_pleaselogin'] = 'Vous n\'&amp;ecirc;tes pas identifi&amp;eacute;. Merci de vous connecter!';
$langs['session_tooold'] = 'Vous avez &amp;eacute;t&amp;eacute; inactif trop longtemps - merci de vous identifier &amp;agrave; nouveau!';
$langs['session_nopermissions'] = 'Vous n\'avez pas le droit de voir ce site!';
$langs['session_already'] = 'Vous &amp;ecirc;tes d&amp;eacute;j&amp;agrave; connect&amp;eacute;!';
$langs['pleasechange'] = 'S\'il vous pla&#238;t changer votre mot de passe afin qu\'il puisse &#234;tre enregistr&#233; avec une nouvelle m&#233;thode de salage et de hachage, nous avons r&#233;cemment mis en place. Cette nouvelle méthode de salage et de hachage est plus dynamique et plus forte.';
$langs['httpapi_noserver'] = 'S\'il vous pla&#238;t insérer l\'adresse du serveur-EMail ou Server-ID.';
$langs['httpapi_notvalidserver'] = 'Adresse serveur mail est incorrect.';
$langs['httpapi_noapikey'] = 'S\'il vous pla&#238;t ins&#233;rer l\'API-Key &#224; partir du serveur.';
$langs['httpapi_logs'] = 'S\'il vous pla&#238;t ins&#233;rer des fichiers journaux, et plus de 20 signes et plus de 3 lignes.';
$langs['httpapi_ip'] = 'S\'il vous pla&#238;t ins&#233;rez le Attacker-IP ou l\'adresse IP est invalide.';
$langs['httpapi_serverunknown'] = 'Erreur sur le serveur de données, fausse adresse e-mail, faux server-id ....?';
$langs['httpapi_senderapi'] = 'L\'API-Key est pas le Api-Key à partir du serveur.';
$langs['httpapi_reported10'] = 'Adresse IP est déjà signalé à partir de votre serveur dans les 10 dernières minutes.';
$langs['httpapi_noservice'] = 'S\'il vous plaît choisir le service contestée.';
$langs['httpapi_serverempty'] = 'S\'il vous plaît ajouter votre serveur-ID ou Server-De-Adresse.';
$langs['httpapi_help'] = '
        <h2>English:</h2><br />
    Call: <strong>http://www.blocklist.de/en/httpreports.html?</strong>
    <br />
    <h3>required Variables:</h3>
    <br />
        <strong>email</strong>: string (E-Mailaddress from Server or ID)
        <br />
        <strong>apikey: </strong> string (in your Profil under SERVER)
        <br />
        <strong>ip</strong>: string (ipv4/ipv6 Address) (Attacker)
        <br />
        <strong>service: </strong> string (Service which was attacked (ssh, imap, ftp...))
        <br />
        <strong>logs</strong>: text (Logfiles)
                <br />
                <strong>format</strong>: text, json, php, xml (Error-Message/OK-Message/Return-Values format)
<br />
<br />
    Version 0.0.0.1

';
$langs['utitle_home'] = 'Quel est www.BlockList.de?';
$langs['utitle_search'] = 'Recherche IP ou AS num&#233;ros sur blocklist.de';
$langs['utitle_contact'] = 'Contactez-nous &#224; propos de questions, des souhaits, Bugs...';
$langs['utitle_contact_sent'] = 'Message envoy&#233; avec succ&#232;s';
$langs['utitle_searchresult'] = 'Recherche-R&#233;sultat IP ou AS num&#233;ros';
$langs['utitle_partners'] = 'Partenaires/Sponsors de www.blocklist.de';
$langs['utitle_statistics'] = 'Statistiques concernant les attaques signal&#233;es';
$langs['utitle_statisticsmonth'] = 'Statistiques pour le mois en cours';
$langs['utitle_statisticsgraph'] = 'Statistiques graphiques';
$langs['utitle_graph'] = 'Statistiques graphiques';
$langs['utitle_insert'] = 'Arr&#234;tez les rapports pour 7 Jours';
$langs['utitle_login'] = 'Connectez-vous &#224; votre profil';
$langs['utitle_register'] = $langs['title_register'];
$langs['utitle_register1'] = $langs['title_register1'];
$langs['utitle_registere'] = $langs['title_register2'];
$langs['utitle_resend'] = 'Renvoyer la confirmation-Mail';
$langs['utitle_delist'] = 'Retirer IP tot dans la liste';
$langs['utitle_api'] = 'API/RBL/DNS de www.blocklist.de';
$langs['utitle_rbldns'] = 'Utilisation de blocklist sur DNS/RBL plus rapide';
$langs['utitle_downloads'] = 'Notre d&#233;claration-Tool et autres t&#233;l&#233;chargements';
$langs['utitle_httpreports'] = 'Rapports Attacker sur Get-/POST-Demandes';
$langs['utitle_export'] = 'Exporter tous les IPs bloqu&#233;s';
$langs['utitle_imprint'] = 'Imprint from www.blocklist.de';
$langs['utitle_userlogin'] = $langs['utitle_login'];
$langs['utitle_terms'] = 'Our Terms and Privacy Policy';
$langs['utitle_register.resend'] = 'Renvoyer la confirmation-Mail';
$langs['utitle_register.confirm'] = 'Inscription Étape 2 de 2';
$langs['utitle_register.block'] = 'Enregistrement étape 2 de 2 (blocage)';
$langs['utitle_password'] = 'Crée un nouveau mot de passe';
$langs['utitle_view'] = 'Voir les attaques de l\'IP: '.htmlspecialchars(trim(@$_GET['ip']));
$langs['utitle_xarf-validator'] = 'X-ARF Validator';
$langs['utitle_xarf-validator-report'] = 'X-ARF Validator for the Yaml-Reports';
$langs['utitle_profile_replace'] = 'Remplacer les données de vos rapports';
$langs['utitle_profile_index'] = 'Server Management/Profil';
$langs['utitle_profile_server'] = 'Votre serveur actif';
$langs['utitle_profile_server.edit'] = 'Ajouter/modifier votre serveur';
$langs['utitle_profile_server.delete'] = 'Supprimer un serveur';
$langs['utitle_profile_whitelist'] = 'IP Whitelist';
$langs['utitle_profile_statistics'] = 'Statistiques du serveur (Own Server)';
$langs['utitle_profile_change'] = 'Modifiez votre profil/paramètres';
$langs['utitle_profile_delete'] = 'Supprimer votre compte';
$langs['utitle_profile_reports'] = 'daily-/mensuelle-/hebdomadaire- Rapports de synthèse';
$langs['utitle_profile_server.list'] = 'Résultat pour le serveur {$serverid} Counts: {$maxcounts} temps complet';
$langs['utitle_profile_allstats'] = 'Statistiques graphiques tous les utilisateurs';
$langs['utitle_logout'] = 'Vous avez été déconnecté.';
$langs['utitle_profile_logout'] = 'Vous avez été déconnecté.';
$langs['title_profile'] = 'Votre Connexion/Profil sur blocklist.de';
$langs['utitle_profile'] = $langs['title_profile'];
$langs['utitle_error'] = 'Erreur: déconnexion automatique';
$langs['export_all'] = 'Toutes les adresses IP ayant attaqu&amp;eacute;es un de vos serveurs dans les 48 derni&amp;egrave;res heures.';
$langs['export_ssh'] = 'Toutes les adresses IP nous ayant &amp;eacute;t&amp;eacute; rapport&amp;eacute; comme ayant attaqu&amp;eacute;es le service SSH.';
$langs['export_mail'] = 'Toutes les IP qui ont &amp;eacute;t&amp;eacute; remont&amp;eacute;es ces 48 derni&amp;egrave;res heures suite &amp;agrave; des attaques sur les serveurs mails, Postfix ...';
$langs['export_apache'] = 'Toutes les IP qui ont &amp;eacute;t&amp;eacute; remont&amp;eacute;es dans les 48 derni&amp;egrave;res heures suite &amp;agrave; des attaques sur le service Apache, Apache-DDOS, RFI-Attacks ...';
$langs['export_bots'] = 'Toutes les adresses IP qui ont &amp;eacute;t&amp;eacute; report&amp;eacute;es durant les derni&amp;egrave;res 48 heures ont g&amp;eacute;n&amp;eacute;r&amp;eacute;es des attaques RFI-Attacks, REG-Bots, IRC-Bots or BadBots (BadBots = spam post&amp;eacute; sur un forum ou un wiki ouvert; Reg-Bots = s\'est enregistr&amp;eacute;).';
$langs['export_imap'] = 'Toutes les adresses IP qui ont été signalés au cours des dernières 48 heures pour les attaques sur le imap Service, sasl, pop3 .....';
$langs['export_ftp'] = 'Toutes les adresses IP qui ont été signalés au cours des dernières 48 heures pour des attaques sur le service FTP.';
$langs['export_asterisk'] = 'All IP addresses that tried to login in a SIP-, VOIP- or Asterisk-Server and are inclueded in the IPs-List from <a href=&quot;https://twitter.com/#!/voipabuse&quot; title=&quot;http://www.infiltrated.net/&quot;>http://www.infiltrated.net/</a> (Twitter).';
$langs['title_trylater'] = '&amp;Agrave; venir. S\'il vous pla&amp;icirc;t attendre quelques jours';
$langs['title_rbldns'] = 'Utilisez le IP-List sur DNS (rbldnsd) pour bloquer les IP plus rapide';
$langs['title_httpreports'] = 'Rapport Attaques sur GET-/POST-Demande de blocklist.de sans Fail2Ban ou E-mail';
$langs['contact'] = 'typS&amp;eacute;lectionnez un sujet svp.';
$langs['data'] = 'sucessDaten wurden erfolgreich Aktualisiert.';
$langs['delete'] = 'confirmBest?tigungslink zum l?schen Ihres Accounts';
$langs['delist'] = 'sucessIP erfolgreich als gefixt markiert und aus der Liste (Download) entfernt (in den n&auml;chsten 10 Minuten).';
$langs['disable'] = 'subjectE-Mailadresse auf www.blocklist.de gesperrt.';
$langs['error'] = 'systemDie &uuml;bergebenen Daten stimmen nicht mit unserem System &uuml;berein.';
$langs['insert'] = 'tolateEs ist kein Angriff mehr f&uuml;r die IP gespeichert..... l&auml;nger als 14 Tage her?';
$langs['login'] = 'subjectUser-Login zu Ihrer Server-Verwaltung';
$langs['password'] = 'tooldDer Link wurde leider nicht innerhalb von 12 Stunden best&auml;tigt. Bitte erstellen Sie sich einen neuen.';
$langs['profil'] = 'logoutVous avez &amp;eacute;t&amp;eacute; d&amp;eacute;connect&amp;eacute;.';
$langs['register'] = 'tooldVotre lien a plus de 7 jours. Merci de cr&amp;eacute;er une nouvelle inscription.';
$langs['replace'] = 'tosmalWert muss l&auml;nger als 3 Zeichen sein!';
$langs['resend'] = 'tomuchD&amp;eacute;sol&amp;eacute;, mais nous avons d&amp;eacute;j&amp;agrave; envoy&amp;eacute; un mail de confirmation dans les derni&amp;egrave;res minutes. Merci de r&amp;eacute;essayer plus tard.';
$langs['search'] = 'takealookBitte pr&uuml;fen Sie auch die Liste von <a href=&quot;http://honeystats.info/glastopf_rbldnsd.zone&quot; title=&quot;Honeystats.info RFI-Attacks&quot;>http://honeystats.info/</a>, wenn die Suche kein Ergebnis zuruecklieferte.';
$langs['server'] = 'usetimeBitte Zeitzone vom Server ausw&auml;hlen.';
$langs['session'] = 'toooldVous avez &amp;eacute;t&amp;eacute; inactif trop longtemps - merci de vous identifier &amp;agrave; nouveau!';
$langs['title'] = 'httpapiIP de l\'attaquant Rapport adresses via http (GET/POST).';
$langs['whitelist'] = 'tosmalWert muss l&auml;nger als 3 Zeichen sein!';
