
          <h1>ADMIN-Tools von blocklist.de</h1>
          <br />


Hier gibts ein paar Tools, wor&uuml;ber man blocklist.de verwalten, IPs l&ouml;schen, whitelisten oder sich die Logs anzeigen kann....

<br />
<br />
<br />

<strong>IP/Blacklist/Whitelist-Stuff</strong>
<br />
<a href="/de/profil/admin/suche.html?{$sid}" title="IP, RID, EMail, Report suchen....">Suche (IP, RID, EMail, Report, Logs...)</a>
<br />
<a href="/de/profil/admin/whitelist.html?{$sid}" title="IP-Adresse whitelisten">globale Whitelist</a>
<br />
<a href="/de/profil/admin/blacklist.html?{$sid}" title="IP/E-Mailadresse global fuer Reports sperren">globale Blacklist</a>
<br />
<a href="/de/profil/admin/replace.html?{$sid}" title="Replacing (Adressen, Logs, Title/Subject, Logs in Body....">Replace</a>
<br />
<br />

<br />
<strong>User/Server Verwaltung</strong>
<br />
<a href="/de/profil/admin/user.html?{$sid}" title="User nach ID, E-Mailadresse, Name suche">User-Suche</a>
<br />
<a href="/de/profil/admin/server.html?{$sid}" title="Server nach ID, E-Mailadresse, Name, IP-Adresse suche">Server-Suche</a>
<br />
<br />

<strong>System-Zeugs</strong>
<br />
<a href="https://otrs.blocklist.de/otrs/index.pl" target="_blank" title="Otrs-Ticket-System fuer abuse-team@, autogenerated@ und support@">Ticket-System</a>
<br />
<a href="/de/profil/admin/load.html?{$sid}" title="Load von den Servern anzeigen lassen">Load der blocklist-Server</a>
<br />

<br />
<br />

